version: "3.5"

x-logging:
    &default-logging
    driver: "json-file"
    options:
        max-size: "5m"
        max-file: "1"

services:

    web:
        container_name: "nginx"
        image: "localhost/web"
        build: "./zanbaldwin/docker-srv/images/web"
        restart: "unless-stopped"
        links: [ "php" ]
        ports: [ "80:80" ]
        volumes: [ "./:/srv/public:ro" ]
        environment:
            AUTOINDEX: "on"
        logging: *default-logging

    php:
        container_name: "php"
        image: "localhost/php"
        command: [ "php-fpm", "-d", "zend_extension=xdebug.so", "--allow-to-run-as-root", "--nodaemonize" ]
        build: "./zanbaldwin/docker-srv/images/php"
        restart: "unless-stopped"
        links: [ "mysql", "neo4j", "redis" ]
        volumes: [ "./:/srv/public" ]
        working_dir: "/srv/public"
        user: "${UID:-1000}"
        environment:
            TERM: xterm
        logging: *default-logging

    mysql:
        container_name: "mysql"
        image: "localhost/mysql"
        build: "./zanbaldwin/docker-srv/images/mysql"
        command: [ "--default-authentication-plugin", "mysql_native_password" ]
        ports: [ "3306:3306" ]
        restart: "unless-stopped"
        volumes: [ "/var/lib/mysql:/var/lib/mysql" ]
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        logging: *default-logging

    neo4j:
        container_name: "neo4j"
        image: "neo4j:3.3.2"
        restart: "unless-stopped"
        volumes: [ "/var/lib/neo4j:/data" ]
        ports: [ "7474:7474", "7687:7687" ]
        environment:
            NEO4J_AUTH: "none"
        logging: *default-logging

    redis:
        container_name: "redis"
        image: "redis:3.2.11-alpine"
        restart: "unless-stopped"
        volumes: [ "/var/lib/redis:/data" ]
        ports: [ "6379:6379" ]
        logging: *default-logging

    mitm:
        image: "mitmproxy/mitmproxy:2.0.2"
        container_name: "mitm"
        ports: [ "8080:8080", "8081:8081" ]
        volumes: [ "${HOME}/.mitmproxy:/home/mitmproxy/.mitmproxy" ]
        command: [ "mitmweb", "--web-iface", "0.0.0.0", "--web-debug" ]
        logging: { driver: "none" }

    registry:
        image: "registry:2.6.2"
        container_name: "registry"
        restart: "unless-stopped"
        ports: [ "5000:5000" ]
        volumes:
            - "/var/lib/registry:/var/lib/registry"

networks:
    default:
        name: "localhost"
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                -   subnet: 10.29.0.0/24
